spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:9530/dm_tmp?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: